### ISSUE TITLE
Flow 101 & 102 DOCKER_LOCALHOST broken on linux

### ISSUE THREAD

**Issue by shaunsmith** [mjg123/mjg123.github.io#3]
A portable expression you can use that works on both Linux and Mac is:

`DOCKER_LOCALHOST=$(docker network inspect bridge -f '{{range .IPAM.Config}}{{.Gateway}}{{end}}')`

The current expression only works on Mac but on Linux is null which means the URLs constructed are broken.

**Comment by mjg123** [comment]
Huh. I did all my testing on linux. Thanks for the update though.
